#!/usr/bin/env python3
"""Extract domain snapshot from reverse-engineered constants + light JS/config scrape.

Writes `.specify/ontology/snapshots/domain.snapshot.json`.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from ontology_map import DIRECTORY_CODES, ENTITY_TO_CLASS  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
SNAPSHOT = ROOT / ".specify" / "ontology" / "snapshots" / "domain.snapshot.json"
CONFIG_EXAMPLE = ROOT / "config.example.json"
SERVER_JS = ROOT / "server.js"
FILE_SERVICE_JS = ROOT / "fileService.js"
UPLOAD_SERVICE_JS = ROOT / "src" / "services" / "uploadService.js"

SOURCE_FILES = [
    ROOT / "server.js",
    ROOT / "files.js",
    ROOT / "fileService.js",
    ROOT / "auth.js",
    ROOT / "config.js",
    ROOT / "config.example.json",
    ROOT / "index.js",
    ROOT / "src" / "services" / "uploadService.js",
]


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.is_file() else ""


def source_sha() -> str:
    h = hashlib.sha256()
    for path in SOURCE_FILES:
        if path.is_file():
            h.update(path.read_bytes())
        h.update(b"\0")
        h.update(str(path.relative_to(ROOT)).encode())
    return h.hexdigest()


def canonical() -> dict:
    live = [
        "StoredFile",
        "Directory",
        "UploadRequest",
        "SidecarMetadata",
        "ApiCredential",
        "FilenameEncodedUpload",
        "ProjectBoundUpload",
    ]
    target = [
        "WindowsShare",
        "Project",
        "ProjectTemplate",
        "ProjectCache",
    ]
    return {
        "$schemaComment": "AUTO-GENERATED by .specify/scripts/extract_domain_snapshot.py — DO NOT HAND-EDIT.",
        "version": "0.1.0-baseline",
        "source": "reverse-engineered from server.js, fileService.js, uploadService.js, config.example.json",
        "sourceSha256": source_sha(),
        "directories": list(DIRECTORY_CODES),
        "poRegex": r"^\d{5}-\d{2}$",
        "filenameGrammar": "DIRECTORY_SHIPMENT_TIMESTAMP_HASH.ext",
        "imageMimes": [
            "image/jpeg",
            "image/png",
            "image/gif",
            "image/bmp",
            "image/webp",
        ],
        "entities": {
            "live": live,
            "target": target,
        },
        "entityMap": dict(ENTITY_TO_CLASS),
    }


def verify_against_sources(snapshot: dict) -> list[str]:
    issues: list[str] = []
    cfg = _read(CONFIG_EXAMPLE)
    server = _read(SERVER_JS)
    file_svc = _read(FILE_SERVICE_JS)
    upload = _read(UPLOAD_SERVICE_JS)

    if cfg:
        try:
            data = json.loads(cfg)
            paths = [d["path"].upper() for d in data.get("directories", [])]
            if paths != list(snapshot["directories"]):
                issues.append(
                    f"directories drift: config={paths} snapshot={snapshot['directories']}"
                )
        except json.JSONDecodeError as exc:
            issues.append(f"config.example.json parse error: {exc}")
    else:
        issues.append("missing config.example.json")

    if file_svc and "DIRECTORY_SHIPMENT_TIMESTAMP_HASH" not in file_svc:
        if "Invalid filename format" not in file_svc:
            issues.append("fileService.js missing filename grammar markers")

    if server:
        for mime in snapshot["imageMimes"]:
            if mime not in server:
                issues.append(f"server.js missing mime {mime}")

    if upload and snapshot["poRegex"] not in upload and r"\d{5}-\d{2}" not in upload:
        issues.append("uploadService.js missing PO regex")

    for name in snapshot["entities"]["live"] + snapshot["entities"]["target"]:
        if name not in ENTITY_TO_CLASS:
            issues.append(f"entity {name} missing from ontology_map.ENTITY_TO_CLASS")

    return issues


def main() -> int:
    snap = canonical()
    issues = verify_against_sources(snap)
    if issues:
        for i in issues:
            print(f"error: {i}", file=sys.stderr)
        return 1
    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT.write_text(json.dumps(snap, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {SNAPSHOT.relative_to(ROOT)} sha={snap['sourceSha256'][:12]}…")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
