#!/usr/bin/env python3
"""Generate structural TBox + directory enum SHACL from domain.snapshot.json.

Do not hand-edit outputs — regenerate after snapshot changes.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ONTOLOGY = ROOT / ".specify" / "ontology"
SNAPSHOT = ONTOLOGY / "snapshots" / "domain.snapshot.json"
GENERATED = ONTOLOGY / "files_domain.generated.ttl"
ENUMS = ONTOLOGY / "files_domain.shacl.enums.ttl"

NS = "https://aes-lighting.com/ns/files#"
GEN_IRI = "https://aes-lighting.com/ns/files/generated"
ENUM_IRI = "https://aes-lighting.com/ns/files/shacl/enums"

CLASS_LABELS = {
    "StoredFile": "Stored File",
    "Directory": "Directory",
    "UploadRequest": "Upload Request",
    "SidecarMetadata": "Sidecar Metadata",
    "ApiCredential": "API Credential",
    "FilenameEncodedUpload": "Filename Encoded Upload",
    "ProjectBoundUpload": "Project Bound Upload",
    "WindowsShare": "Windows Share",
    "Project": "Project",
    "ProjectTemplate": "Project Template",
    "ProjectCache": "Project Cache",
}

DATA_PROPS = [
    ("directoryCode", "string"),
    ("originalFilename", "string"),
    ("storagePath", "string"),
    ("fileSize", "integer"),
    ("poNumber", "string"),
    ("projectNumber", "string"),
    ("shipmentId", "string"),
    ("contentHash", "string"),
    ("mimeType", "string"),
    ("apiKeyHint", "string"),
]


def _ttl_list(values: list[str]) -> str:
    return " ".join(f'"{v}"' for v in values)


def build_generated(snap: dict) -> str:
    sha = snap["sourceSha256"]
    lines = [
        "# AUTO-GENERATED by .specify/scripts/generate_ontology.py — DO NOT HAND-EDIT.",
        f"@prefix files: <{NS}> .",
        "@prefix owl:  <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .",
        "@prefix dct:  <http://purl.org/dc/terms/> .",
        "",
        f"<{GEN_IRI}>",
        "    a owl:Ontology ;",
        '    dct:title "file-service-client generated TBox" ;',
        f'    owl:versionInfo "{snap.get("version", "0.1.0-baseline")}" ;',
        f'    rdfs:comment "sourceSha256={sha}" .',
        "",
        "files:LiveSurface a owl:Class ; rdfs:label \"Live Surface\" .",
        "files:TargetSurface a owl:Class ; rdfs:label \"Target Surface\" .",
        "files:FilenameEncodedSurface a owl:Class ; rdfs:label \"Filename Encoded Surface\" .",
        "files:ProjectBoundUploadSurface a owl:Class ; rdfs:label \"Project Bound Upload Surface\" .",
        "files:ProjectDiscoverySurface a owl:Class ; rdfs:label \"Project Discovery Surface\" .",
        "files:PublicHealthSurface a owl:Class ; rdfs:label \"Public Health Surface\" .",
        "files:AiRawAdvice a owl:Class ; rdfs:label \"AI Raw Advice\" .",
        "",
    ]

    for name in snap["entities"]["live"]:
        label = CLASS_LABELS.get(name, name)
        lines.append(
            f'files:{name} a owl:Class ; rdfs:label "{label}" ; rdfs:subClassOf files:LiveSurface .'
        )
    lines.append("")
    for name in snap["entities"]["target"]:
        label = CLASS_LABELS.get(name, name)
        lines.append(
            f'files:{name} a owl:Class ; rdfs:label "{label}" ; rdfs:subClassOf files:TargetSurface .'
        )
    lines.append("")

    for prop, xsd in DATA_PROPS:
        lines.append(
            f"files:{prop} a owl:DatatypeProperty ; rdfs:range xsd:{xsd} ; rdfs:label \"{prop}\" ."
        )
    lines.append("")
    return "\n".join(lines)


def build_enums(snap: dict) -> str:
    dirs = snap.get("directories") or []
    return "\n".join(
        [
            "# AUTO-GENERATED by .specify/scripts/generate_ontology.py — DO NOT HAND-EDIT.",
            f"@prefix files: <{NS}> .",
            "@prefix owl:  <http://www.w3.org/2002/07/owl#> .",
            "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
            "@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .",
            "@prefix sh:   <http://www.w3.org/ns/shacl#> .",
            "@prefix dct:  <http://purl.org/dc/terms/> .",
            "",
            f"<{ENUM_IRI}>",
            "    a owl:Ontology ;",
            '    dct:title "Files Domain SHACL Directory Enums" ;',
            f'    owl:versionInfo "{snap.get("version", "0.1.0-baseline")}" ;',
            f'    rdfs:comment "sourceSha256={snap["sourceSha256"]}" .',
            "",
            "files:DirectoryCodePropertyShape",
            "    a sh:PropertyShape ;",
            "    sh:path files:directoryCode ;",
            "    sh:datatype xsd:string ;",
            "    sh:minCount 1 ;",
            "    sh:maxCount 1 ;",
            f"    sh:in ( {_ttl_list(dirs)} ) .",
            "",
        ]
    )


def main() -> int:
    if not SNAPSHOT.is_file():
        print(f"error: missing {SNAPSHOT}", file=sys.stderr)
        return 1
    snap = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    GENERATED.write_text(build_generated(snap), encoding="utf-8")
    ENUMS.write_text(build_enums(snap), encoding="utf-8")
    print(f"wrote {GENERATED.relative_to(ROOT)}")
    print(f"wrote {ENUMS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
